language: c
env:
    matrix:
        - python=2.7
        - python=3.3

install:
    - source .travis-install.sh
    - "sudo rm -rf /dev/shm && sudo ln -Tsf /run/shm /dev/shm"

script: bash sphinx-doctests

branches:
    only:
        - master
